behaviors:
  BaseShooterAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 50
      buffer_size: 5000
      learning_rate: 3.0e-4
      beta: 0.0004
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000